### ISSUE TITLE
Failing to load an Ontology into WissKI Ontology Configuration

### ISSUE THREAD

**Issue by berndl** [WissKI/wisski_pathbuilder#4]
Hi!

First of all, sorry if I created this issue in the wrong repository, I did not know which one would fit best! (Feel free to move it anywhere else! :))

I am trying to install a WissKI system following the instructions found on "http://wiss-ki.eu/installation_guide", reaching the bullet point "Configuring your WissKI system".

I followed all the instructions up to that point, but a default “SPARQL 1.1 with Pathbuilder” adapter is never found under the “WissKI Salz Adapters” tab, although the module “WissKI SPARQL 1.1 adapter with pathbuilder” is installed. So i tried to create one by hand, which presumably succeeds.

Now when I try to do the next step of adding an ontology via the respective administration page, I instantly get prompted with the error message
**Something went wrong in 'doQuery' for adapter "pathbuilder_test"**
with "pathbuilder_test" being my chosen name for the pathbuilder adapter.

Checking the log messages of drupal, this is the output of the error message:
`query "SELECT DISTINCT ?ont (COALESCE(?niri, 'none') as ?iri) (COALESCE(?nver, 'none') as ?ver) ?graph WHERE { GRAPH ?graph { ?ont a owl:Ontology } . OPTIONAL { ?ont owl:ontologyIRI ?niri. } OPTIONAL { ?ont owl:versionIRI ?nver . } }" caused error: EasyRdf_Exception: Failed to parse HTTP response status line. in /var/www/html/drupal/vendor/easyrdf/easyrdf/lib/EasyRdf/Http/Response.php:286 Stack trace: #0 /var/www/html/drupal/vendor/easyrdf/easyrdf/lib/EasyRdf/Http/Client.php(467): EasyRdf_Http_Response::fromString('HTTP/1.1 200 \r\n...') #1 /var/www/html/drupal/modules/wisski/wisski_salz/src/Plugin/wisski_salz/Engine/WissKI_Sparql_Client.php(113): EasyRdf_Http_Client->request() #2 /var/www/html/drupal/vendor/easyrdf/easyrdf/lib/EasyRdf/Sparql/Client.php(120): Drupal\wisski_salz\Plugin\wisski_salz\Engine\WissKI_Sparql_Client->request('query', 'SELECT DISTINCT...') #3 /var/www/html/drupal/modules/wisski/wisski_salz/src/Plugin/wisski_salz/Engine/Sparql11Engine.php(281): EasyRdf_Sparql_Client->query('SELECT DISTINCT...') #4 /var/www/html/drupal/modules/wisski/wisski_salz/src/Plugin/wisski_salz/Engine/Sparql11Engine.php(275): Drupal\wisski_salz\Plugin\wisski_salz\Engine\Sparql11Engine->doQuery('SELECT DISTINCT...') #5 /var/www/html/drupal/modules/wisski/wisski_adapter_sparql11_pb/src/Plugin/wisski_salz/Engine/Sparql11EngineWithPB.php(2848): Drupal\wisski_salz\Plugin\wisski_salz\Engine\Sparql11Engine->directQuery('SELECT DISTINCT...') #6 /var/www/html/drupal/modules/wisski/wisski_core/src/Form/WisskiOntologyForm.php(97): Drupal\wisski_adapter_sparql11_pb\Plugin\wisski_salz\Engine\Sparql11EngineWithPB->getOntologies() #7 [internal function]: Drupal\wisski_core\Form\WisskiOntologyForm->buildForm(Array, Object(Drupal\Core\Form\FormState)) #8 /var/www/html/drupal/core/lib/Drupal/Core/Form/FormBuilder.php(514): call_user_func_array(Array, Array) #9 /var/www/html/drupal/core/lib/Drupal/Core/Form/FormBuilder.php(364): Drupal\Core\Form\FormBuilder->retrieveForm('WisskiOntologyF...', Object(Drupal\Core\Form\FormState)) #10 /var/www/html/drupal/core/lib/Drupal/Core/Form/FormBuilder.php(621): Drupal\Core\Form\FormBuilder->rebuildForm('WisskiOntologyF...', Object(Drupal\Core\Form\FormState), Array) #11 /var/www/html/drupal/core/lib/Drupal/Core/Form/FormBuilder.php(314): Drupal\Core\Form\FormBuilder->processForm('WisskiOntologyF...', Array, Object(Drupal\Core\Form\FormState)) #12 /var/www/html/drupal/core/lib/Drupal/Core/Controller/FormController.php(74): Drupal\Core\Form\FormBuilder->buildForm('WisskiOntologyF...', Object(Drupal\Core\Form\FormState)) #13 [internal function]: Drupal\Core\Controller\FormController->getContentResult(Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\RouteMatch)) #14 /var/www/html/drupal/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array) #15 /var/www/html/drupal/core/lib/Drupal/Core/Render/Renderer.php(576): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #16 /var/www/html/drupal/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure)) #17 /var/www/html/drupal/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) #18 [internal function]: Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #19 /var/www/html/drupal/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Object(Closure), Array) #20 /var/www/html/drupal/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #21 /var/www/html/drupal/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #22 /var/www/html/drupal/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #23 /var/www/html/drupal/core/modules/page_cache/src/StackMiddleware/PageCache.php(99): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #24 /var/www/html/drupal/core/modules/page_cache/src/StackMiddleware/PageCache.php(78): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true) #25 /var/www/html/drupal/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #26 /var/www/html/drupal/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(50): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #27 /var/www/html/drupal/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #28 /var/www/html/drupal/core/lib/Drupal/Core/DrupalKernel.php(657): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #29 /var/www/html/drupal/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #30 {main}`

I also get the same basic error message when I try to add a new path to my pathbuilder, also stating that I do not yet have an ontology added (I can also support the error message, if necessary).

As my knowledge about all the technologies is very limited, I wanted to ask if maybe I did something wrong in advance, maybe in the configuration? Is this a known error?

I am glad for any help, please let me know if I can provide further input for this problem.

Thanks and best regards,
Manu

**Comment by mnscholz** [comment]
Hi Manu,

the exception says that the easyrdf lib (which is used for
communication with the triple store) "Failed to parse HTTP response
status line. "

This very likely means that either your triple store is not set up
properly or that the URL for reading from the triple store is not
correct.

What kind of triple store do you use?
What URL is in the read/write URL fields of your adapter?

Martin
<div id="DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2"><br /> <table
style="border-top: 1px solid #D3D4DE;">
	<tr>
      <td style="width: 55px; padding-top: 18px;"><a
href="https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail"
target="_blank"><img
src="https://ipmcdn.avast.com/images/icons/icon-envelope-tick-round-orange-animated-no-repeat-v1.gif"
alt="" width="46" height="29" style="width: 46px; height: 29px;"
/></a></td>
		<td style="width: 470px; padding-top: 17px; color: #41424e;
font-size: 13px; font-family: Arial, Helvetica, sans-serif;
line-height: 18px;">Virenfrei. <a
href="https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail"
target="_blank" style="color: #4453ea;">www.avast.com</a> 		</td>
	</tr>
</table>
<a href="#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2" width="1" height="1"></a></div>

2018-01-10 15:56 GMT+01:00 Emanuel Berndl <notifications@github.com>:

**Comment by berndl** [comment]
Hi @mnscholz ,
thank you for your very quick answer!
I am using a blazegraph triplestore (https://www.blazegraph.com/) and now that you mention it, I indeed was not quite sure what to enter for the read and write URLs.

What is supposed to be entered there, the triplestore's SPARQL/query/update URL? 

Best regards,
Manu

**Comment by mnscholz** [comment]
Yes, the read url field requires the sparql query url and the write field
the update url, resp.

In Blazegraph you can get them from the service description of the
namespace you use, and -- if i am not mistaken -- they are both the same in
blazegraph. (I haven't been using blazegraph for quite a while now...)

Martin

2018-01-11 10:08 GMT+01:00 Emanuel Berndl <notifications@github.com>:

**Comment by berndl** [comment]
Hi again!
You were right with the service description of blazegraph, but I could not get it running. Maybe I have yet misconfigured something there. So i swapped to an Apache Jena Fuseki (https://jena.apache.org/documentation/fuseki2/index.html) instance for further testing.

With that I managed to support correct read and write endpoints (so no error message when I try to upload an ontology), however the upload of the ontology does not work. After supporting an OWL file, I receive conflicting feedback of both an error and success, see the screenshot:

![screen shot 2018-01-12 at 20 14 08](https://user-images.githubusercontent.com/7922417/34891265-39e63df0-f7d5-11e7-85b0-2fd0b36b1080.png)

I also copied the error message of the logs again:

[ontologyUploadException.txt](https://github.com/WissKI/wisski_pathbuilder/files/1627195/ontologyUploadException.txt)

In the description of the Wisski installation there was also the possibility listed of adding the triples by hand to the triplestore, but this did also not succeed. I uploaded the triples but got an error message when trying to create a path of the respective path builder, indicating that there is no ontology present.

I tried to use the most recent versioned namespace of the Erlangen CRM, found at "http://erlangen-crm.org/ontology/ecrm/ecrm_170309.owl".

Am I supporting an incorrect link to the OWL file? Did I miss some configuration?

Manu

**Comment by mnscholz** [comment]
Hi,

in the exception message of the ontologyUploadException.txt
<https://github.com/WissKI/wisski_pathbuilder/files/1627195/ontologyUploadException.txt>
, there is the hint that "Error 400: Could not initialize class
org.apache.jena.riot.web.HttpOp Fuseki - version 2.6.0 (Build date:
2017-05-02T17:38:25+0000)".

So there seems something missing in Jena itself. Have you hd a look into
the Jena log files? Have you tried uploading some rdf file into the repo
using Jena's standard
html interface? Does that work?

Martin

2018-01-12 21:17 GMT+01:00 Emanuel Berndl <notifications@github.com>:

**Comment by berndl** [comment]
Hi,
I have tried uploading the schema file directly, which succeeded from the database side, but WissKI did not seem to recognise the triples or an ontology being there.

I will look into the log files of the Fueski (which will take some time because it is not hosted by myself :-D).

In the meantime: Could you please give me a suggestion of a (at best non-commercial :-) ) triplestore that you commonly use with WissKI?

Thanks in advance, best,
Manu

**Comment by mnscholz** [comment]
Hi again,

we use rdf4j with the native store.

from the exception you posted before and the working direct upload I would
guess, fusekis sparql endpoint is not set up correctly. can you retrieve
data from it, eg. with wget or curl?

Martin




2018-01-15 13:49 GMT+01:00 Emanuel Berndl <notifications@github.com>:

**Comment by berndl** [comment]
Hi !
This issue has been solved.
Thanks a lot again for your help, Martin and Mark!

For future reference, if this problem would come up again, I'll try to summarise it. The comment by Knurg solved it: [link to github issue](https://github.com/njh/easyrdf/issues/278).

I am using Tomcat with version 8.5.24 (version 8.5.x seems to have the issue), and there a problem occurs in the HTTP communication with Drupal/WissKI. So it was necessary to apply the patch of the github link from above to the Response.php file of the Drupal installation (roughly at the location drupal/vendor/easyrdf/easyrdf/lib/EasyRdf/Http/Response.php:286).

Best,
Manu
